apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbook
  template:
    metadata:
      labels:
        app: cloudbook
    spec:
      containers:
        - name: cloudbook
          image: tanmaydubey552001/cloudbook:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:h2:file:/data/h2db/cloudbook;DB_CLOSE_ON_EXIT=FALSE
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          volumeMounts:
            - name: h2-data
              mountPath: /data/h2db
      volumes:
        - name: h2-data
          persistentVolumeClaim:
            claimName: h2-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: cloudbook-service
spec:
  selector:
    app: cloudbook
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080